apiVersion: v1
kind: Service
metadata:
  name: epi-bf
  labels:
    app: epi-bf
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: epi-bf
    tier: proxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: epi-proxy
  labels:
    service-monitor: epi-proxy
spec:
  selector:
    matchLabels:
      app: epi-proxy
  endpoints:
  - port: web
    interval: 10s
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: epi-bf-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: epi-bf
  minReplicas: {{ .Values.bf_custom_hpa.minReplicas }}
  maxReplicas: {{ .Values.bf_custom_hpa.maxReplicas }}
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: epi-proxy
      metricName: {{ .Values.bf_custom_hpa.metricName }}
      targetValue: {{ .Values.bf_custom_hpa.targetValue }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: epi-config
  namespace: epi
data:
  EPI_SERVER: "epi-server"
  EPI_SERVER_PORT: "80"
  EPI_VNF: "epi-bf"
  EPI_VNF_PORT: "5000"
  PROXY_HOST: "epi-proxy"
  PROXY_PORT: "1080"
  DELTA: "5.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-bf
  namespace: epi
spec:
  replicas: TOTAL_REPLICAS
  selector:
   matchLabels:
    app: epi-bf
  template:
    metadata:
      labels:
        app: epi-bf
        tier: proxy
    spec:
      containers:
      - name: epi-bf
        image: "{{ .Values.bf.image }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "{{ .Values.bf.cpu_limit }}"
            memory: "{{ .Values.bf.mem_limit }}"
          requests:
            cpu: "{{ .Values.bf.cpu_request }}"
            memory: "{{ .Values.bf.mem_request }}"
        volumeMounts:
          - name: bf-pv
            mountPath: /mnt
      volumes:
        - name: bf-pv
          hostPath:
            path: /root
            type: Directory
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: epi-proxy
  namespace: default
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /epi-proxy
        backend:
          serviceName: epi-proxy
          servicePort: 80
---

# melamin/epi-proxy:v0.01
# pimpaardekooper/vnf_instances:proxy
