apiVersion: v1
kind: Service
metadata:
  name: epi-server
  labels:
    app: epi-server
    tier: server
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: epi-server
    tier: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-server
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-server
  template:
    metadata:
      labels:
        app: epi-server
        tier: server
    spec:
      containers:
      - name: epi-server
        image: pimpaardekooper/vnf_instances:server
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 100Mi
