apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: epi
data: 
  config.yaml: |
    rules:
    - seriesQuery: 'number_of_requests{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
