apiVersion: v1
kind: ConfigMap
metadata:
  name: epi-config
  namespace: epi
data:
  EPI_SERVER: "epi-server"
  EPI_SERVER_PORT: "80"
  EPI_VNF_FW: "epi-firewall"
  EPI_VNF_FW_PORT: "5000"
  PROXY_HOST: "epi-proxy"
  PROXY_PORT: "1080"