---
apiVersion: v1
kind: Service
metadata:
  name: epi-proxy
  labels:
    app: epi-proxy
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 1080
    name: socks
  - port: 80
    targetPort: 80
    name: web
  selector:
    app: epi-proxy
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-proxy
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-proxy
  template:
    metadata:
      labels:
        app: epi-proxy
        tier: proxy
    spec:
      containers:
      - name: epi-proxy
        image: pimpaardekooper/vnf_instances:proxy
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 1080
        - containerPort: 80
        securityContext:
          privileged: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: epi-proxy
  labels:
    service-monitor: epi-proxy
spec:
  selector:
    matchLabels:
      app: epi-proxy
  endpoints:
  - port: web
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: epi-firewall-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: epi-firewall
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: epi-proxy
      metricName: http_requests
      targetValue: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-firewall
  namespace: epi
spec:
  replicas: 2
  selector:
   matchLabels:
    app: epi-firewall
  template:
    metadata:
      labels:
        app: epi-firewall
        tier: firewall
    spec:
      containers:
      - name: epi-firewall
        image: pimpaardekooper/vnf_instances:firewall
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: epi-proxy
  namespace: default
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /epi-proxy
        backend:
          serviceName: epi-proxy
          servicePort: 80

# melamin/epi-proxy:v0.01
# pimpaardekooper/vnf_instances:proxy