---
apiVersion: v1
kind: Service
metadata:
  name: epi-proxy
  labels:
    app: epi-proxy
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 1080
  selector:
    app: epi-proxy
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-proxy
  namespace: epi
spec:
  replicas: REPLICAS
  selector:
   matchLabels:
    app: epi-proxy
  template:
    metadata:
      labels:
        app: epi-proxy
        tier: proxy
    spec:
      containers:
      - name: epi-proxy
        image: melamin/epi_proxy:v0.0.3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 1080
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: LIMITS_CPU
            memory: LIMITS_MEM
          requests:
            cpu: REQUEST_CPU
            memory: REQUEST_MEM