apiVersion: v1
kind: Service
metadata:
  name: epi-bf
  labels:
    app: epi-bf
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: epi-bf
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-bf
  namespace: epi
spec:
  replicas: REPLICAS
  selector:
   matchLabels:
    app: epi-bf
  template:
    metadata:
      labels:
        app: epi-bf
        tier: proxy
    spec:
      containers:
      - name: epi-bf
        # image: melamin/epi_vnf_http_filter:v0.0.9
        # image: melamin/epi_vnf_network_monitor:v0.0.9
        #image: melamin/epi_vnf_firewall:v0.0.7
        image: pimpaardekooper/vnf_instances:http_filter_no_stress
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: LIMITS_CPU
            memory: LIMITS_MEM
          requests:
            cpu: REQUEST_CPU
            memory: REQUEST_MEM
        securityContext:
          privileged: true
        volumeMounts:
          - name: bf-pv
            mountPath: /mnt
      volumes:
        - name: bf-pv
          hostPath:
            path: /root
            type: Directory
