apiVersion: v1
kind: Service
metadata:
  name: epi-server
  labels:
    app: epi-server
    tier: server
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: epi-server
    tier: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-server
  namespace: epi
spec:
  replicas: REPLICAS
  selector:
   matchLabels:
    app: epi-server
  template:
    metadata:
      labels:
        app: epi-server
        tier: server
    spec:
      containers:
      - name: epi-server
        image: melamin/httpbin:v0.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: LIMITS_CPU
            memory: LIMITS_MEM
          requests:
            cpu: REQUEST_CPU
            memory: REQUEST_MEM