---
apiVersion: v1
kind: Service
metadata:
  name: epi-client
  labels:
    app: epi-client
    tier: client
  namespace: epi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: epi-client
    tier: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-client
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-client
  template:
    metadata:
      labels:
        app: epi-client
        tier: client
    spec:
      containers:
      - name: epi-client
        image: melamin/epi-client:v0.10
        envFrom:
        - configMapRef:
            name: epi-client-config
        ports:
        - containerPort: 80
        securityContext:
          privileged: true