apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: epi-bf-hpa
  namespace: epi
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: epi-bf
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50