---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: epi-firewall-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: epi-firewall
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 200m
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-firewall
  namespace: epi
spec:
  replicas: 2
  selector:
   matchLabels:
    app: epi-firewall
  template:
    metadata:
      labels:
        app: epi-firewall
        tier: firewall
    spec:
      containers:
      - name: epi-firewall
        image: pimpaardekooper/vnf_instances:firewall
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
