---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: networkmonitor-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: epi-networkmonitor
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-networkmonitor
  namespace: epi
spec:
  replicas: 2
  selector:
   matchLabels:
    app: epi-networkmonitor
  template:
    metadata:
      labels:
        app: epi-networkmonitor
        tier: proxy
    spec:
      containers:
      - name: epi-networkmonitor
        image: pimpaardekooper/vnf_instances:network_monitor
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true

