---
apiVersion: v1
kind: Service
metadata:
  name: epi-firewall
  labels:
    app: epi-firewall
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: epi-firewall
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-firewall
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-firewall
  template:
    metadata:
      labels:
        app: epi-firewall
        tier: proxy
    spec:
      containers:
      - name: epi-firewall
        image: melamin/epi_vnf_firewall:v0.0.3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
