apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: epi-bf-hpa
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: epi-bf
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
  # Default HPA poilcy Behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max