---
apiVersion: v1
kind: Service
metadata:
  name: epi-bf
  labels:
    app: epi-bf
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: epi-bf
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-bf
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-bf
  template:
    metadata:
      labels:
        app: epi-bf
        tier: proxy
    spec:
      containers:
      - name: epi-bf
        #image: pimpaardekooper/vnf_instances:network_monitor
        image: melamin/epi_vnf_firewall:v0.0.4
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        securityContext:
          privileged: true
