---
apiVersion: v1
kind: Service
metadata:
  name: epi-ratelimiter
  labels:
    app: epi-ratelimiter
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  clusterIP: 10.96.0.4
  ports:
  - port: 5000
  selector:
    app: epi-ratelimiter
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-ratelimiter
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-ratelimiter
  template:
    metadata:
      labels:
        app: epi-ratelimiter
        tier: proxy
    spec:
      containers:
      - name: epi-ratelimiter
        image: pimpaardekooper/vnf_instances:rate_limiter
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        env:
          - name: BITRATE
            value: 0.01mbps

