---
apiVersion: v1
kind: Service
metadata:
  name: epi-proxy
  labels:
    app: epi-proxy
    tier: proxy
  namespace: epi
spec:
  type: ClusterIP
  ports:
  - port: 1080
    name: socks
  - port: 80
    name: http
  selector:
    app: epi-proxy
    tier: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-proxy
  namespace: epi
spec:
  replicas: 1
  selector:
   matchLabels:
    app: epi-proxy
  template:
    metadata:
      labels:
        app: epi-proxy
        tier: proxy
    spec:
      containers:
      - name: epi-proxy
        image: melamin/vnf_instances:proxy
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: epi-config
        ports:
        - containerPort: 1080
        - containerPort: 80
        securityContext:
          privileged: true

# melamin/epi-proxy:v0.01
# pimpaardekooper/vnf_instances:proxy